name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    backend-ci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: '24'
            - name: Install dependencies
              run: npm install
            - name: Check Styles
              run: npm run lint
    frontend-ci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: '24'
            - name: Install dependencies
              run: npm install
            # - name: Run Component test
            #   run: npm test